### ISSUE TITLE
Link to full documentation is broken

### ISSUE THREAD

**Issue by TonioGarcia07** [openmobilityfoundation/mds-compliance-mobile#6]
Hello, the link in the readme is broken: it points to https://github.com/openmobilityfoundation/mds-compliance-mobile/blob/master/Compliance-Mobile-Instructions.pdf, which is a 404.

Could you update the link please ? :)

**Comment by sarob** [comment]
Hi @twelch 
Are there Compliance Mobile Instructions separate from the instructions in the README or should the reference be removed from the README?

**Comment by twelch** [comment]
Hi @sarob 👋 I've added a PR to remove the link for now.  There is a PDF user manual that was in the works but I haven't been able to track down from the owner and get an ETA with the holiday upon us.  If you feel strongly this issue can stay open until its added.

**Comment by sarob** [comment]
That’s okay with me to remove the link. I recommend you add creating the user manual to your backlog and commenting back to the GitHub issue. Cheers!

~ sean
